// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, unused_import
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXMB41vPYl-ENS-ngGZBZ_9TZbhZoJqng',
    appId: '1:180398693843:web:441280a7da3afb4b1fa326',
    messagingSenderId: '180398693843',
    projectId: 'hms-med',
    authDomain: 'hms-med.firebaseapp.com',
    storageBucket: 'hms-med.appspot.com',
    measurementId: 'G-SCL4WDS3MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtpTwabCSdtnJ-TyEmG1KZMzE88Ju1m_w',
    appId: '1:180398693843:android:1540370b106f2dcc1fa326',
    messagingSenderId: '180398693843',
    projectId: 'hms-med',
    storageBucket: 'hms-med.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB12CBPT6UDH4n-27vk-nwGD2fi5QikRW8',
    appId: '1:180398693843:ios:d4e94bcd6cadb5ab1fa326',
    messagingSenderId: '180398693843',
    projectId: 'hms-med',
    storageBucket: 'hms-med.appspot.com',
    iosClientId: '180398693843-3r7qhlaqlojlrd39uoln2o9bs31faui0.apps.googleusercontent.com',
    iosBundleId: 'com.km.team.hms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB12CBPT6UDH4n-27vk-nwGD2fi5QikRW8',
    appId: '1:180398693843:ios:d4e94bcd6cadb5ab1fa326',
    messagingSenderId: '180398693843',
    projectId: 'hms-med',
    storageBucket: 'hms-med.appspot.com',
    iosClientId: '180398693843-3r7qhlaqlojlrd39uoln2o9bs31faui0.apps.googleusercontent.com',
    iosBundleId: 'com.km.team.hms',
  );
}
